---
- name: Install Node Exporter
  vars:
    node_exporter_filename: node_exporter-{{ node_exporter_version }}.linux-amd64.tar.gz
    node_exporter_dir: node_exporter-{{ node_exporter_version }}.linux-amd64
  block:
    - name: Check if Node Exporter binary exists
      ansible.builtin.stat:
        path: /usr/local/bin/node_exporter
      register: node_exporter_binary

    - name: Download Node Exporter binary
      ansible.builtin.get_url:
        url: https://github.com/prometheus/node_exporter/releases/download/v{{ node_exporter_version }}/{{ node_exporter_filename }}
        dest: /tmp/{{ node_exporter_filename }}
        mode: '0644'
      when: not node_exporter_binary.stat.exists

    - name: Unarchive the Node Exporter binary
      ansible.builtin.unarchive:
        src: /tmp/{{ node_exporter_filename }}
        dest: /tmp
        remote_src: true
      when: not node_exporter_binary.stat.exists

    - name: Copy Node Exporter binary to /usr/local/bin
      ansible.builtin.copy:
        src: /tmp/{{ node_exporter_dir }}/node_exporter
        dest: /usr/local/bin/node_exporter
        mode: '0755'
        owner: root
        group: root
        remote_src: true
      when: not node_exporter_binary.stat.exists

    - name: Clean up downloaded tarball and extracted directory
      ansible.builtin.file:
        path: "{{ item }}"
        state: absent
      loop:
        - /tmp/{{ node_exporter_filename }}
        - /tmp/{{ node_exporter_dir }}
      when: not node_exporter_binary.stat.exists

    - name: Add dedicated Node Exporter user
      ansible.builtin.user:
        name: node_exporter
        shell: /bin/false
        create_home: false
        system: true

    - name: Create Systemd unit file
      ansible.builtin.template:
        src: service.j2
        dest: /etc/systemd/system/node_exporter.service
        mode: '0644'

    - name: Start the service unit
      ansible.builtin.systemd_service:
        state: started
        enabled: true
        daemon_reload: true
        name: node_exporter
