---
# https://argo-cd.readthedocs.io/en/stable/operator-manual/installation/
- name: Install essential packages
  ansible.builtin.apt:
    name:
      - python3
      - python3-kubernetes

- name: Create ArgoCD namespace
  kubernetes.core.k8s:
    name: argocd
    api_version: v1
    kind: Namespace
    state: present

- name: Download argocd manifest to the cluster.
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/argoproj/argo-cd/{{ argocd_version }}/manifests/install.yaml
    dest: /tmp/install.yaml
    mode: "0664"

# Manifest taken from https://github.com/argoproj/argo-cd/releases
- name: Apply argocd manifest to the cluster.
  kubernetes.core.k8s:
    namespace: argocd
    state: present
    src: /tmp/install.yaml
    server_side_apply:
      field_manager: ansible
      force_conflicts: true

# We do this patch to connect to the ArgoCD server via URL and not port-forward
- name: Patch the Configmap to insecure
  kubernetes.core.k8s:
    state: patched
    kind: ConfigMap
    namespace: argocd
    name: argocd-cmd-params-cm
    definition:
      data:
        server.insecure: "true"

# Rollout restart for the patch to take effect
- name: Restart ArgoCD Server after patch
  kubernetes.core.k8s:
    state: patched
    kind: Deployment
    name: argocd-server
    namespace: argocd
    definition:
      spec:
        template:
          metadata:
            annotations:
              kubectl.kubernetes.io/restartedAt: "{{ now(fmt='%Y-%m-%dT%H:%M:%SZ') }}"

- name: Wait for ArgoCD server pod to be ready
  kubernetes.core.k8s:
    definition:
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: argocd-server
        namespace: argocd
    wait: true
    wait_sleep: 5
    wait_timeout: 180

- name: Template the ingressroute manifest to /tmp
  ansible.builtin.template:
    src: ingressroute.yaml.j2
    dest: /tmp/ingressroute.yaml

- name: Apply the IngressRoute manifest
  kubernetes.core.k8s:
    state: present
    src: /tmp/ingressroute.yaml

- name: Template the apps-of-apps manifest to /tmp
  ansible.builtin.template:
    src: root-app.yaml.j2
    dest: /tmp/root-app.yaml

- name: Apply the Apps Of Apps ArgoCD manifest
  kubernetes.core.k8s:
    state: present
    src: /tmp/root-app.yaml

- name: Get initial ArgoCD password
  kubernetes.core.k8s_info:
    api_version: v1
    kind: Secret
    name: argocd-initial-admin-secret
    namespace: argocd
  register: argocd_admin_password

- name: Print admin credentials
  ansible.builtin.debug:
    msg:
      - "=============================="
      - "Username: admin"
      - "Password: {{ argocd_admin_password.resources[0].data.password | b64decode }}"
      - "=============================="
