---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-creds
  namespace: monitoring
spec:
  encryptedData:
    admin-password: AgAuxCBwop81InAL7lwhd2p18t+z0W1jregDYcrhSRbBdBQzW0cH8POCnJKPxW5u5mKxBER6V7E3q1z1ZGArkSNBFvnRjSSHcrcO8ndSKPBFC6eeflpKw6hRzXp/Q3XPE0YSIB/1vjwrDQlzme04DBpVVM0K6/8Cu87cW282jlPo1t0purzsOf+2nUK8bxcqxUpihKvpihDA7bSyha72IeG9EPoGpQV7Z8bXrAEQ9GONEocJTkdQBVNpsJJVBe695/yo/wB5pDJh2d9j1wqVdBSRhL2bV2uh+dQ7rFzrddNNN0LBJqfyp9h3twymNAtjolAc+IHB1XmXDYd9/lP5shZe7AbEeSYNQ5eC+mfRte0AqC8t1R0zEEZgIDv6XNR5a/ZwZTeZcGL/Iq1VboPHgSc6OucbgLEupl6kBF+43mgYjZoBIonyRP1We+BqquGrcwVVJduaRNXmLAjLLGTziJm5Aia4imGaLr4GZnydJOjrina0CChQfnbYsY+FPwu3u39hZYOrohtHbPUwZHeav4t50sp8j1335DwpmJYnZDhSyoIZGmy+wLx2asp6f4X6zdxyuFaVC46A/8K4DBGJttwkTfMgCqg45Qmm7rIeqVK/ecAJ6o6YtfXyggXPlchNtnqBoCUyANUjKGsSbs+s44mUa8UF324lP6Jg5eIdW9ve8bYfQDed6YJEk16Ih6gxyr4IO5RBYEAXFXfcayG2lu/r # gitleaks:allow
    admin-user: AgBcm+wqFKImt2vxy0OxZ0gyCnO5wUJpiWJM6Wql+jpAkTUObQ7h3ADxoTWzOttvNTHh+Q/RBlShUbuXRNZW+ZZyq6S4zaxnFQ1pHG6omSP1i/Cy3lf2gWgu/AgN8s+k8ySA4H0fP8L7752gnLx62X6LAuURijobdRTODbMaXims6ukx0LEFZ5VBVRGppJ5Uf9sWQLxcWE0Bx7Q0DttGXgWR2M4vzxxBZQ5cmU5KBHLHzO67Pu7zk4bOb3uO0h/ve0ekE+aOFPl83Tl4V5YBi6Gs/nuEE9WO0os/K2qhMhoIdHIFrxfXXdxE2JReXD5EC9IMmgNoxua58CCs1j3Fpcmtn7xVNfQ+dlk34yYUGXOfINe0yVnv1zR9HsJRWQ+ixDY7Wdc1e5L5ZBxf4K93DNaaU391Xob6UMX2pS/u5tjDiP46EXnkgVP49SwvCs8TexP8cdWNAtpumjAJvnDbV7d03nGcUD/7hYfnE9Rq7zZm5sUWKit2KGtOBRBQyzvVSggb33OJ5vx0urx8mVp+uTIctHKQYrlignuVLa2UgHytkr6hmaLbp5QeN/kxxzi38I7zLqp4LrjueFkUo0zqwxxHrI9LsLzx5wG7wW0muV7g+27vZaobq/3K4wd9/g6fQdjZmHDLARpavJaWN/XVU0IR1LMY9NrfxMTerjxJp3ZQw6L7YwYqyOmo4SaMTGRKXMPqZ5EqnA== # gitleaks:allow
  template:
    metadata:
      name: grafana-creds
      namespace: monitoring
    type: Opaque
