---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: discord-webhook-url
  namespace: gatus
spec:
  encryptedData:
    DISCORD_WEBHOOK_URL: AgAFs4fRWXlknPDlYhfm/EU57XVVM013krIdRkcZMWAnZ1zm241471mMaLHkTnreldOQMHK8+bVMR8QLR4H2nlIJ+4f+Je+byRHt2aSGNP63+LJ0BSkbQ8z9wCX1p4nx6yTmnkTJol8covomYunz57qI8xAOi9G6Yk40tsqRQI7kr4duI66s4x/qtaSsvhWLIY1NuX/U0SUMfAl9Xcolfc9MqPzrKrTJANPb1Ff+fADgzNpPYuYj7jnaHZNKR40yI4+7qa9N0DofLDonvgBBRuLRYY6dXmZMC69gl0zhFQaACroTgZd8JOrnz/VuvkcXSXe79teQFROm3afmBTWSUfZo4veUVrKBX+AJp/C7FptXSMWC88Mv1X7wVwPb/mwTv5nngOX7AZGKG4vALH1joARtDtUDBOys2oX56XlbzbeVSvAbcJtn83lgrhXCWi7nJIBTRe9Fhpx1KXc/dXdbxQvx7hELFecs0Oct3F05Mgdfu4IySbGSlI1x5kM+Wm/t5V9bbT2Cr8Jjv8E4idXPqiXbSqnSORLA2+IJkSXtR9maYPaYdFcOU78i6OB80YfRyTicfbH4bmp/ffz8GE7kwgqAtH5nvxp5iP5VP5S95ZMAP0yktIn5M6YfCVLBXWkPDzKO21dTowUMKJXUGOKigy3fZ0rproUP9ol0laO2UYS8KOK24iy+UGISjnIl62hN9RZOYQnq8en4V+HRBZEq4c36y3p2zp/QsG5lxFntUTzSNYHtP6TB3hAjfxIELHnATjJIfAYwiyigVtHAAbkqUs21pwIxhi1PltNR22URKh3RV7vUkLCTor7iN9j4n62d2FccjfWn489DodmJk3nFiNykcK1TFAFkq65y
  template:
    metadata:
      name: discord-webhook-url
      namespace: gatus
