---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: tailscale-auth
  namespace: uptimekuma
spec:
  encryptedData:
    TS_AUTHKEY: AgBCo1YFay/liqmfNGSPzJcoEeg+nU373I0w7X8yCLrIHsF7GrsX45wlF1LuBpeHcjfndJn7cjAxv4mgn5RWdXXiBthX6Qz9aS4ZjGtSS2BW5n/DzSWBoK8xdsJuVxVosQINv6DWFRt8ZlFqb2khBD3C6kV2QvFgyWEcBeRfIvnb0KUx7fkRNWN7lmGEK4Gu5b+3xEusFQbL2YqoLEVoHfhpDHnz5L6cqyABoqm3rMnUZt9FiFD/DCU5CtWi/wghnQomWQDJwuB54B1bEulotIHj5oZXDbMVBE7Oj38jKht7tzqYTtuotcDfABlyhGonHH3pxoa9xtLXdm0eGElgieYxuB4BMVSWf8tI89WDFS7JeSqbnnGad99uosc/I4AkKsGGME/V4uMKdjzNA9mGlgqmT8FUz8Ot9Uxqg61gxZAcQBURuqBZYIaQiAdEX5LMYkltugFMnH6+4pk1u7CqAZ+6wisS6+SgTpNqKpi0E5TIUf/redwPkNg65PZgTpFKl7qMJ/DLapWhHF5tPdXXySbLFdr0Mf+ztDceWM85lePFAcGOj2ugWyFs1UKpcqWKtLf06X1Vs9EpTTxYPmXEVN7d+Q4KCjj88uU6YySmVqCEBovaMES9izNf9+Eg4GL+crSrUk2w/ipNeAtM1AfLajfFrvBZ1Qt+oTlA5A7tdiiQcFPR/UuCbg0NulnpwM8ArVbNuLkjlF3qocbf6EPWBmFmNAWeB7K0UA2W41wliP87l0Jl922EMUP3YRkYeUBZmwEK8/Oh//ZX2XN1q78P # gitleaks:allow
  template:
    metadata:
      name: tailscale-auth
      namespace: uptimekuma
