---
- name: Init VMs
  hosts: all
  become: true
  roles:
    - system_init
    - monitoring
  tags: init

- name: Configure firewall rules for VMs
  hosts: all
  become: true
  roles:
    - firewall
  tags: security

- name: Deploy K3s cluster
  import_playbook: k3s.orchestration.site
  tags: k3s

- name: Install ArgoCD on cluster
  environment:
    K8S_AUTH_KUBECONFIG: "/home/ubuntu/.kube/config"
  hosts: server
  roles:
    - argocd
  tags: argocd
