---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gatus
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/tTomeRr/homelab
    targetRevision: HEAD
    path: apps/gatus
  destination:
    server: https://kubernetes.default.svc
    namespace: gatus
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
