---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: trivy-operator
  namespace: argocd
spec:
  project: default
  source:
    repoURL: "https://aquasecurity.github.io/helm-charts/"
    chart: trivy-operator
    targetRevision: 0.33.1
    helm:
      releaseName: trivy-operator
      apiVersions:
        - monitoring.coreos.com/v1
      values: |
        trivy:
          severity: "HIGH CRITICAL"
          ignoreUnfixed: true
        serviceMonitor:
          enabled: true
  destination:
    server: https://kubernetes.default.svc
    namespace: trivy-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
